### ISSUE TITLE
gitignore 적용 요망

### ISSUE THREAD

**Issue by o-ozogie** [FakeInstagram/Backend#3]
.idea나 .DS_Store 파일이 어떤 역할을 하나요? 역할이 없다면 원격 저장소에 그런 파일이 올라오지 않게 하기 위해서는 어떻게 하는게 좋을까요?

**Comment by kjbin0420** [comment]
민감한 파일이나 역할이 없는 파일들은 gitignore을 해야겠네요!

**Comment by o-ozogie** [comment]
적용하고 이슈 close 해주세용:)
