### ISSUE TITLE
git flow 적용 고려

### ISSUE THREAD

**Issue by woochanleee** [FakeInstagram/Backend#4]
두 분이 함께 개발하는걸로 보이는데
이럴때 파일이 겹치는 등 문제가 나서 고생하는걸 방지하기 위해
git flow 전략을 알아보고 적용해 보는걸 고려해 봅시다!😊
[우아한형제들 기술 블로그](https://woowabros.github.io/experience/2017/10/30/baemin-mobile-git-branch-strategy.html)

**Comment by kjbin0420** [comment]
감사합니다!!
